apiVersion: v1
kind: PersistentVolume
metadata:
  name: gdms-mysql-claim
  labels:
    type: local
spec:
  storageClassName: suibian
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
