apiVersion: v1
kind: Service
metadata:
  name: golangdemomicroserviceredis
spec:
  selector:
    app: golangdemomicroserviceredis
  ports:
    - protocol: TCP
      port: 26379
      targetPort: 6379
      nodePort: 30002
  type: NodePort
  