apiVersion: v1
kind: Service
metadata:
  name: golangdemomicroserviceuser
spec:
  selector:
    app: golangdemomicroserviceuser
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 8080
  type: LoadBalancer
  